title: 东北林业大学转专业经验分享站
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  本科生院链接: https://bksy.nefu.edu.cn/

# 语言 & 时区
lang: zh-CN
timezone: Asia/Shanghai

# 让主题去 _data/zh-CN.yml 找词
locale: zh-CN
